/*
  # Seed OGS Students

  ## Summary
  Creates class records, Supabase Auth user accounts, user profiles, 
  and inserts all 308 students from the Okrika Grammar School student roll.
  
  Passwords are set to 'School@2025' and emails are dynamically generated.
*/

DO $$
DECLARE
  v_school_id uuid := (SELECT id FROM schools LIMIT 1);
  v_ay_id     uuid := (SELECT id FROM academic_years LIMIT 1);
  cid_jss1a   uuid;
  cid_jss1b   uuid;
  cid_jss2    uuid;
  cid_jss3    uuid;
  cid_sss1    uuid;
  cid_sss2    uuid;
  cid_sss3    uuid;
  
  student RECORD;
  v_id uuid;
  v_email text;
BEGIN

  INSERT INTO public.classes (id, school_id, name, level, section, capacity, academic_year_id) VALUES
    (gen_random_uuid(), v_school_id, 'JSS 1 A', 'JSS1', 'A', 50, v_ay_id),
    (gen_random_uuid(), v_school_id, 'JSS 1 B', 'JSS1', 'B', 50, v_ay_id),
    (gen_random_uuid(), v_school_id, 'JSS 2',   'JSS2', 'A', 50, v_ay_id),
    (gen_random_uuid(), v_school_id, 'JSS 3',   'JSS3', 'A', 50, v_ay_id),
    (gen_random_uuid(), v_school_id, 'SSS 1',   'SS1',  'A', 70, v_ay_id),
    (gen_random_uuid(), v_school_id, 'SSS 2',   'SS2',  'A', 50, v_ay_id),
    (gen_random_uuid(), v_school_id, 'SSS 3',   'SS3',  'A', 50, v_ay_id)
  ON CONFLICT DO NOTHING;

  SELECT id INTO cid_jss1a FROM public.classes WHERE school_id = v_school_id AND name = 'JSS 1 A' LIMIT 1;
  SELECT id INTO cid_jss1b FROM public.classes WHERE school_id = v_school_id AND name = 'JSS 1 B' LIMIT 1;
  SELECT id INTO cid_jss2  FROM public.classes WHERE school_id = v_school_id AND name = 'JSS 2' LIMIT 1;
  SELECT id INTO cid_jss3  FROM public.classes WHERE school_id = v_school_id AND name = 'JSS 3' LIMIT 1;
  SELECT id INTO cid_sss1  FROM public.classes WHERE school_id = v_school_id AND name = 'SSS 1' LIMIT 1;
  SELECT id INTO cid_sss2  FROM public.classes WHERE school_id = v_school_id AND name = 'SSS 2' LIMIT 1;
  SELECT id INTO cid_sss3  FROM public.classes WHERE school_id = v_school_id AND name = 'SSS 3' LIMIT 1;

  FOR student IN SELECT * FROM (VALUES
    ('OGS001', 'Peculiar', 'Amakiri', cid_jss1a, 'A'),
    ('OGS002', 'Aribibia', 'Angel', cid_jss1a, 'A'),
    ('OGS003', 'Daniel C', 'Adele', cid_jss1a, 'A'),
    ('OGS004', 'Tamunoibiyemieari Treasure', 'Atuboyedia', cid_jss1a, 'A'),
    ('OGS005', 'Jefferson O', 'Christopher', cid_jss1a, 'A'),
    ('OGS006', 'Abdulhakeem Aminayanasa', 'Yakubu', cid_jss1a, 'A'),
    ('OGS007', 'Ibisiki', 'David', cid_jss1a, 'A'),
    ('OGS008', 'Tamunofekerebia', 'Gloria', cid_jss1a, 'A'),
    ('OGS009', 'GodsWill', 'Samuel I', cid_jss1a, 'A'),
    ('OGS010', 'Daniel', 'West', cid_jss1a, 'A'),
    ('OGS011', 'Testimony C', 'Samuel', cid_jss1a, 'A'),
    ('OGS012', 'Izu', 'Ogoruma', cid_jss1a, 'A'),
    ('OGS013', 'Dorcas', 'Monday', cid_jss1a, 'A'),
    ('OGS014', 'Kingsley', 'Ikechukwu', cid_jss1a, 'A'),
    ('OGS015', 'Oghasoro Destiny', 'Culbuokeru', cid_jss1a, 'A'),
    ('OGS016', 'Happiness', 'Augustine', cid_jss1a, 'A'),
    ('OGS017', 'David', 'Ambai', cid_jss1a, 'A'),
    ('OGS018', 'Precious Gift', 'Kalio', cid_jss1a, 'A'),
    ('OGS019', 'Churchill', 'GodStime', cid_jss1a, 'A'),
    ('OGS020', 'Favour Ayika', 'Boma', cid_jss1a, 'A'),
    ('OGS021', 'Raphael T.', 'George', cid_jss1a, 'A'),
    ('OGS022', 'Ugbana', 'Samuel', cid_jss1a, 'A'),
    ('OGS023', 'Emmanuella', 'Ikechukwu', cid_jss1a, 'A'),
    ('OGS024', 'Soibifaa', 'Jaja', cid_jss1a, 'A'),
    ('OGS025', 'Victory Clari', 'Abokiri', cid_jss1a, 'A'),
    ('OGS026', 'Arikpo Charity', 'Okem', cid_jss1a, 'A'),
    ('OGS027', 'Favour', 'Innocent', cid_jss1a, 'A'),
    ('OGS028', 'Francisa', 'Tamunoiyowuna', cid_jss1a, 'A'),
    ('OGS029', 'Daniel GodSwill', 'Monday', cid_jss1a, 'A'),
    ('OGS030', 'Flourish', 'Tamunobelema', cid_jss1a, 'A'),
    ('OGS031', 'Bright Otobong', 'Silas', cid_jss1a, 'A'),
    ('OGS032', 'Tamunoitekena', 'Isaac', cid_jss1a, 'A'),
    ('OGS033', 'Simeon I', 'Sunday', cid_jss1a, 'A'),
    ('OGS034', 'Treasure', 'Dike', cid_jss1a, 'A'),
    ('OGS035', 'Esther Kienabere', 'Deinma', cid_jss1a, 'A'),
    ('OGS036', 'Ekomobong', 'Destiny', cid_jss1a, 'A'),
    ('OGS037', 'Victor', 'Marvellous', cid_jss1a, 'A'),
    ('OGS038', 'Friday Ndifereke', 'Prope', cid_jss1a, 'A'),
    ('OGS039', 'Gideon', 'Monday', cid_jss1a, 'A'),
    ('OGS040', 'Prince T', 'Richard', cid_jss1b, 'B'),
    ('OGS041', 'Rapheal', 'Dominate', cid_jss1b, 'B'),
    ('OGS042', 'James Ibiye', 'Treasure', cid_jss1b, 'B'),
    ('OGS043', 'Tamuno-Dein Thomas', 'David', cid_jss1b, 'B'),
    ('OGS044', 'Opuwar King Giovanni', 'Tamuno-Ibuomie', cid_jss1b, 'B'),
    ('OGS045', 'Nengi', 'Evans', cid_jss1b, 'B'),
    ('OGS046', 'Vivian Chukwuemeka', 'Ifechukuru', cid_jss1b, 'B'),
    ('OGS047', 'Stella', 'Thankgod', cid_jss1b, 'B'),
    ('OGS048', 'Tamunoamiebaka Morgan', 'Beatrice', cid_jss1b, 'B'),
    ('OGS049', 'Morrison', 'Amakiri', cid_jss1b, 'B'),
    ('OGS050', 'Tamunoigbeinbia', 'Osemibi', cid_jss1b, 'B'),
    ('OGS051', 'Treasure', 'GodStime', cid_jss1b, 'B'),
    ('OGS052', 'Justice', 'Jackson', cid_jss1b, 'B'),
    ('OGS053', 'Godgift Johnson', 'Monday', cid_jss1b, 'B'),
    ('OGS054', 'Amalime', 'David', cid_jss1b, 'B'),
    ('OGS055', 'Carissa', 'Strong', cid_jss1b, 'B'),
    ('OGS056', 'Godswill Johnson', 'Patrick', cid_jss1b, 'B'),
    ('OGS057', 'Abraham', 'Goodnews', cid_jss1b, 'B'),
    ('OGS058', 'Miracle', 'David', cid_jss1b, 'B'),
    ('OGS059', 'Silver Abiye', 'Samuel', cid_jss1b, 'B'),
    ('OGS060', 'Princess', 'Achoso', cid_jss1b, 'B'),
    ('OGS061', 'Rejoice Okeme', 'Marcus', cid_jss1b, 'B'),
    ('OGS062', 'Bright', 'Samuel', cid_jss1b, 'B'),
    ('OGS063', 'Emmanuella T', 'Fenibo', cid_jss1b, 'B'),
    ('OGS064', 'Efezino', 'Whisky', cid_jss1b, 'B'),
    ('OGS065', 'Daniella Eneji', 'David', cid_jss1b, 'B'),
    ('OGS066', 'Richard', 'Lazarus', cid_jss1b, 'B'),
    ('OGS067', 'Samartha', 'Strong', cid_jss1b, 'B'),
    ('OGS068', 'Johnson', 'Mary', cid_jss1b, 'B'),
    ('OGS069', 'Benita', 'Strong', cid_jss1b, 'B'),
    ('OGS070', 'Gracious Tamunomiebaka', 'Marcus', cid_jss1b, 'B'),
    ('OGS071', 'Benamebi', 'Derick', cid_jss1b, 'B'),
    ('OGS072', 'Queen Christabel Ibiye', 'Bestman', cid_jss1b, 'B'),
    ('OGS073', 'Wisdom', 'Benjamin', cid_jss1b, 'B'),
    ('OGS074', 'Helen E', 'Tambou', cid_jss1b, 'B'),
    ('OGS075', 'Victory', 'Emmanuel', cid_jss1b, 'B'),
    ('OGS076', 'Amapakabo', 'Blessing', cid_jss1b, 'B'),
    ('OGS077', 'Kelly', 'Rachael', cid_jss1b, 'B'),
    ('OGS078', 'Jumbobaraye', 'Precious', cid_jss1b, 'B'),
    ('OGS079', 'George Joseph', 'Goodness', cid_jss1b, 'B'),
    ('OGS080', 'Attila', 'Kuro', cid_jss1b, 'B'),
    ('OGS081', 'Dagogo Clinton', 'Dominien', cid_jss1b, 'B'),
    ('OGS082', 'Chidi Destiny', 'Chukwudi', cid_jss2, 'A'),
    ('OGS083', 'Deborah T', 'Dede', cid_jss2, 'A'),
    ('OGS084', 'Otimi Precious', 'Tokoni', cid_jss2, 'A'),
    ('OGS085', 'Tamuno Miebaka', 'Soseipirlala', cid_jss2, 'A'),
    ('OGS086', 'Wakirike Tamunoene', 'Rejoice', cid_jss2, 'A'),
    ('OGS087', 'Ndop Godselect', 'Christain', cid_jss2, 'A'),
    ('OGS088', 'GodSgiory Uduak', 'Hanson', cid_jss2, 'A'),
    ('OGS089', 'Ikpoko Danzel', 'Dagogo', cid_jss2, 'A'),
    ('OGS090', 'Peace', 'Godspower', cid_jss2, 'A'),
    ('OGS091', 'Wakama Victoria', 'Tamunobome', cid_jss2, 'A'),
    ('OGS092', 'Cherith T', 'Sunday', cid_jss2, 'A'),
    ('OGS093', 'Peculiar Alamina', 'Daniel', cid_jss2, 'A'),
    ('OGS094', 'Douglas Tennyson', 'Ibitamuno', cid_jss2, 'A'),
    ('OGS095', 'Christabel Boma', 'Iniworikabo', cid_jss2, 'A'),
    ('OGS096', 'Thankgod Ida', 'Erefaka', cid_jss2, 'A'),
    ('OGS097', 'Marvellous Samuel', 'Ugbana', cid_jss2, 'A'),
    ('OGS098', 'Emmanuel', 'Charles', cid_jss2, 'A'),
    ('OGS099', 'Enenembo', 'Ofoti', cid_jss2, 'A'),
    ('OGS100', 'Sanusi', 'Adebayo', cid_jss2, 'A'),
    ('OGS101', 'Destiny Sunday', 'John', cid_jss2, 'A'),
    ('OGS102', 'Great Tokuyanebobusiki', 'Caleb', cid_jss2, 'A'),
    ('OGS103', 'Esther', 'Tamunokuro', cid_jss2, 'A'),
    ('OGS104', 'Sunday Ruth', 'Ibiere', cid_jss2, 'A'),
    ('OGS105', 'Tamunotoku Dakora', 'Roseline', cid_jss2, 'A'),
    ('OGS106', 'Ubani Ogechi', 'Success', cid_jss2, 'A'),
    ('OGS107', 'Anointed Aribibia', 'Ibiokwein', cid_jss2, 'A'),
    ('OGS108', 'Belema Elvis', 'Godfirst', cid_jss2, 'A'),
    ('OGS109', 'GodSdesire T', 'GodSpower', cid_jss2, 'A'),
    ('OGS110', 'Gift Odagie', 'Uwumadie', cid_jss2, 'A'),
    ('OGS111', 'Tamunonengiyeoforiye Greatness', 'Isoboye', cid_jss2, 'A'),
    ('OGS112', 'Blossom', 'Liveth', cid_jss2, 'A'),
    ('OGS113', 'Victor Vincent', 'Oloidi', cid_jss2, 'A'),
    ('OGS114', 'Etiagbedia', 'Joy', cid_jss2, 'A'),
    ('OGS115', 'Israel', 'Asitonka', cid_jss2, 'A'),
    ('OGS116', 'Japhet', 'Ellison', cid_jss2, 'A'),
    ('OGS117', 'King Miebaka', 'Satonye', cid_jss2, 'A'),
    ('OGS118', 'Emmanuel', 'Alexander', cid_jss2, 'A'),
    ('OGS119', 'Frank', 'Miracle', cid_jss2, 'A'),
    ('OGS120', 'Iseamadiema', 'Bright', cid_jss2, 'A'),
    ('OGS121', 'Clinton Bola', 'Oja', cid_jss2, 'A'),
    ('OGS122', 'Increase Iyam', 'Effiom', cid_jss2, 'A'),
    ('OGS123', 'Tamunosemiebi T', 'David', cid_jss2, 'A'),
    ('OGS124', 'Ibifubara', 'Minabo', cid_jss2, 'A'),
    ('OGS125', 'Nnenna', 'Samuel', cid_jss3, 'A'),
    ('OGS126', 'Peculiar T', 'Dike', cid_jss3, 'A'),
    ('OGS127', 'Odanne Chidi', 'Praise', cid_jss3, 'A'),
    ('OGS128', 'Joshua', 'GodSpower', cid_jss3, 'A'),
    ('OGS129', 'Esther Iworibo', 'Wakama', cid_jss3, 'A'),
    ('OGS130', 'Asenath Ene', 'Wakama', cid_jss3, 'A'),
    ('OGS131', 'Onyekachi', 'Bethels', cid_jss3, 'A'),
    ('OGS132', 'Onyekachi', 'Bethels', cid_jss3, 'A'),
    ('OGS133', 'Manassen Boma', 'Golden', cid_jss3, 'A'),
    ('OGS134', 'Dominion', 'David', cid_jss3, 'A'),
    ('OGS135', 'Miracle', 'Sotonye', cid_jss3, 'A'),
    ('OGS136', 'Boma Oscar', 'Boma', cid_jss3, 'A'),
    ('OGS137', 'Ransome O', 'Excellent', cid_jss3, 'A'),
    ('OGS138', 'Mischael Tamuno Miebaka', 'Ogan', cid_jss3, 'A'),
    ('OGS139', 'GodSflavour T', 'GodSpower', cid_jss3, 'A'),
    ('OGS140', 'Precious', 'Owunari', cid_jss3, 'A'),
    ('OGS141', 'David Chedebere', 'Oyebuchi', cid_jss3, 'A'),
    ('OGS142', 'Emmanuel T Abereni', 'Boye', cid_jss3, 'A'),
    ('OGS143', 'Miebaka', 'Peter John', cid_jss3, 'A'),
    ('OGS144', 'Osward Chizaram', 'Ikechukwu', cid_jss3, 'A'),
    ('OGS145', 'Ibi Fubara', 'Amakiri', cid_jss3, 'A'),
    ('OGS146', 'Anionting', 'Teddy', cid_jss3, 'A'),
    ('OGS147', 'Uchendu', 'Prince', cid_jss3, 'A'),
    ('OGS148', 'Princewill', 'Kamsi', cid_jss3, 'A'),
    ('OGS149', 'Mercy', 'DanielS', cid_jss3, 'A'),
    ('OGS150', 'Stephaine Amanna', 'Udochia', cid_jss3, 'A'),
    ('OGS151', 'Osomokie', 'Blossom', cid_jss3, 'A'),
    ('OGS152', 'Ibiyeomieye Olivia', 'Julius', cid_jss3, 'A'),
    ('OGS153', 'Tonye', 'Timothy', cid_jss3, 'A'),
    ('OGS154', 'Destiny', 'Derefaka', cid_jss3, 'A'),
    ('OGS155', 'Pecullar', 'Amakiri', cid_jss3, 'A'),
    ('OGS156', 'Deborah T', 'Aribibia', cid_jss3, 'A'),
    ('OGS157', 'Sarah', 'Plus', cid_jss3, 'A'),
    ('OGS158', 'Slyeofori I', 'Sandra', cid_jss3, 'A'),
    ('OGS159', 'Perfect', 'Tamunonideokuma', cid_jss3, 'A'),
    ('OGS160', 'Princewill', 'Godswill', cid_jss3, 'A'),
    ('OGS161', 'Miracle Neke', 'Anaka', cid_jss3, 'A'),
    ('OGS162', 'Peace', 'Thankgod', cid_jss3, 'A'),
    ('OGS163', 'Farida', 'Hakeen', cid_jss3, 'A'),
    ('OGS164', 'Kallo Revel', 'Abbey', cid_sss1, 'A'),
    ('OGS165', 'Jonah', 'Bakoye', cid_sss1, 'A'),
    ('OGS166', 'Emperor Orafiri', 'Benjamin', cid_sss1, 'A'),
    ('OGS167', 'Divine Tamunobarafiri', 'Brown', cid_sss1, 'A'),
    ('OGS168', 'Awaji Metor', 'Brown', cid_sss1, 'A'),
    ('OGS169', 'Destiny Chukwudi', 'Chidi', cid_sss1, 'A'),
    ('OGS170', 'Divine Poloamina', 'Derefaka', cid_sss1, 'A'),
    ('OGS171', 'Victor', 'David', cid_sss1, 'A'),
    ('OGS172', 'Diemeru Ibimiebo', 'Reign', cid_sss1, 'A'),
    ('OGS173', 'Fortune', 'Iyenemi', cid_sss1, 'A'),
    ('OGS174', 'David', 'Iselema', cid_sss1, 'A'),
    ('OGS175', 'Newton Atawaji', 'Joe', cid_sss1, 'A'),
    ('OGS176', 'Moses', 'Johnson', cid_sss1, 'A'),
    ('OGS177', 'Matthew Sunday', 'Kirizo', cid_sss1, 'A'),
    ('OGS178', 'Prince Tobonemi', 'Miebaka', cid_sss1, 'A'),
    ('OGS179', 'Sunday Bright', 'Monday', cid_sss1, 'A'),
    ('OGS180', 'Benjamin', 'Obinna', cid_sss1, 'A'),
    ('OGS181', 'Friday Destiny', 'Onu', cid_sss1, 'A'),
    ('OGS184', 'Dignity Udoabili', 'Raphaeal', cid_sss1, 'A'),
    ('OGS186', 'Stephen', 'Derefaka', cid_sss1, 'A'),
    ('OGS187', 'Boma', 'Tamunobelema', cid_sss1, 'A'),
    ('OGS188', 'Otuk', 'Udo', cid_sss1, 'A'),
    ('OGS189', 'Emmanuel', 'Itelima', cid_sss1, 'A'),
    ('OGS190', 'Emmanuel', 'Philip', cid_sss1, 'A'),
    ('OGS191', 'Daniel', 'Owafamaka', cid_sss1, 'A'),
    ('OGS192', 'John', 'Onyebuchi', cid_sss1, 'A'),
    ('OGS193', 'Damiete', 'Tamunonegieyoefori', cid_sss1, 'A'),
    ('OGS194', 'Paul', 'Nelson', cid_sss1, 'A'),
    ('OGS195', 'Ibinabo Brilliant', 'Sunny', cid_sss1, 'A'),
    ('OGS196', 'Aisha Yakubo', 'Aminayanasa', cid_sss1, 'A'),
    ('OGS197', 'Olive Ofem', 'Orikpo', cid_sss1, 'A'),
    ('OGS198', 'Victory Ntengi', 'Allanso', cid_sss1, 'A'),
    ('OGS199', 'Mary', 'Alexander', cid_sss1, 'A'),
    ('OGS200', 'Progess', 'Bassey', cid_sss1, 'A'),
    ('OGS201', 'Favour', 'Gift', cid_sss1, 'A'),
    ('OGS202', 'Godsfavour', 'Isaac', cid_sss1, 'A'),
    ('OGS203', 'Lloyo Biebele', 'Ibifuro', cid_sss1, 'A'),
    ('OGS204', 'Briget Ibisabo', 'Inichinbia', cid_sss1, 'A'),
    ('OGS205', 'Chidinmma Nora', 'Isaac', cid_sss1, 'A'),
    ('OGS206', 'Divine', 'Kelechukwu', cid_sss1, 'A'),
    ('OGS207', 'Beulah', 'Liveth', cid_sss1, 'A'),
    ('OGS208', 'Priscilla Ogan', 'Moses', cid_sss1, 'A'),
    ('OGS209', 'Ibinabo Hannah', 'Moses', cid_sss1, 'A'),
    ('OGS210', 'Tamuno Atafyne', 'Minayo', cid_sss1, 'A'),
    ('OGS211', 'Ibinabo Catherine', 'Orisa', cid_sss1, 'A'),
    ('OGS212', 'Rhoda', 'Pius', cid_sss1, 'A'),
    ('OGS213', 'Marian Nengi', 'Sovins', cid_sss1, 'A'),
    ('OGS214', 'Sunday Tamunomiebaka', 'Daka', cid_sss1, 'A'),
    ('OGS215', 'Godness Tobin', 'Tamunobarafiri', cid_sss1, 'A'),
    ('OGS216', 'Sarah', 'Tekena', cid_sss1, 'A'),
    ('OGS217', 'Providence', 'Tamunobelema', cid_sss1, 'A'),
    ('OGS218', 'Princess', 'Tamunobelema', cid_sss1, 'A'),
    ('OGS219', 'Elizabeth', 'Enoch', cid_sss1, 'A'),
    ('OGS220', 'Tamunonengiyeofori', 'Japhet', cid_sss1, 'A'),
    ('OGS221', 'Grace', 'Peace', cid_sss1, 'A'),
    ('OGS222', 'Emmanuella', 'Oyemami', cid_sss1, 'A'),
    ('OGS224', 'Faith', 'Minasechinbo', cid_sss1, 'A'),
    ('OGS225', 'Enoch Tamunoblemabo', 'Atuboyedia', cid_sss1, 'A'),
    ('OGS226', 'Miebaka', 'Timothy', cid_sss1, 'A'),
    ('OGS227', 'Onyekachi', 'Caleb', cid_sss2, 'A'),
    ('OGS228', 'Awesome L', 'Longjohn', cid_sss2, 'A'),
    ('OGS229', 'Kuro Tamunobaraami', 'Joseph', cid_sss2, 'A'),
    ('OGS230', 'Aribibia', 'Saint', cid_sss2, 'A'),
    ('OGS231', 'Tekena', 'Wisdom', cid_sss2, 'A'),
    ('OGS232', 'Fnayefeka', 'James', cid_sss2, 'A'),
    ('OGS233', 'Emmanuel', 'Ibinabo', cid_sss2, 'A'),
    ('OGS234', 'Chikadibie', 'Daniel', cid_sss2, 'A'),
    ('OGS235', 'Tamunobarafiri', 'Peace', cid_sss2, 'A'),
    ('OGS236', 'Chubuike', 'Kanu', cid_sss2, 'A'),
    ('OGS237', 'Chigozie', 'Joshua', cid_sss2, 'A'),
    ('OGS238', 'Godgift T', 'Iseamadiema', cid_sss2, 'A'),
    ('OGS239', 'Desire I', 'Micheal', cid_sss2, 'A'),
    ('OGS240', 'Samuel', 'Godfirst', cid_sss2, 'A'),
    ('OGS241', 'Ebube', 'Emmanuel', cid_sss2, 'A'),
    ('OGS242', 'Aduche', 'Prosper', cid_sss2, 'A'),
    ('OGS243', 'Watter', 'Rotimi', cid_sss2, 'A'),
    ('OGS244', 'Elijha Ubong', 'John', cid_sss2, 'A'),
    ('OGS245', 'David Ubong', 'John', cid_sss2, 'A'),
    ('OGS246', 'Godstime', 'Prosper', cid_sss2, 'A'),
    ('OGS247', 'Bright', 'John', cid_sss2, 'A'),
    ('OGS248', 'Kelvin', 'Nnaemeka', cid_sss2, 'A'),
    ('OGS249', 'George', 'Faith', cid_sss2, 'A'),
    ('OGS250', 'Tamunokuro', 'Emmanuella', cid_sss2, 'A'),
    ('OGS251', 'Ibiyeomie J', 'Success', cid_sss2, 'A'),
    ('OGS252', 'Alamina', 'Cherish', cid_sss2, 'A'),
    ('OGS253', 'Bernard', 'Esther', cid_sss2, 'A'),
    ('OGS254', 'Lucky', 'Oseipriye', cid_sss2, 'A'),
    ('OGS255', 'Shebudec', 'Precious', cid_sss2, 'A'),
    ('OGS256', 'Christabel', 'Paul', cid_sss2, 'A'),
    ('OGS257', 'Dickson', 'Josephine', cid_sss2, 'A'),
    ('OGS258', 'Favour Sunday', 'Divine', cid_sss2, 'A'),
    ('OGS259', 'Nwankwo', 'Nzubechi', cid_sss2, 'A'),
    ('OGS260', 'King Destiny', 'Solomon', cid_sss2, 'A'),
    ('OGS261', 'Oluwakorade', 'Precious', cid_sss2, 'A'),
    ('OGS262', 'Bright', 'Emmason', cid_sss2, 'A'),
    ('OGS263', 'Favour A', 'Siyeofori', cid_sss2, 'A'),
    ('OGS264', 'Gladys T', 'Sylvanus', cid_sss2, 'A'),
    ('OGS265', 'Choguzie', 'Divine', cid_sss2, 'A'),
    ('OGS266', 'Precious', 'Minayo', cid_sss2, 'A'),
    ('OGS267', 'Ngowari Edward', 'Treasure', cid_sss2, 'A'),
    ('OGS268', 'Opekere Sam W', 'Raymond', cid_sss2, 'A'),
    ('OGS269', 'Bestman', 'Daniel', cid_sss3, 'A'),
    ('OGS270', 'Caleb', 'Royal', cid_sss3, 'A'),
    ('OGS271', 'Godwin', 'Treasure', cid_sss3, 'A'),
    ('OGS272', 'Ibibia Alayemieka', 'Samuel', cid_sss3, 'A'),
    ('OGS273', 'Somina', 'Pius', cid_sss3, 'A'),
    ('OGS274', 'Moses', 'IniworikaboOforie', cid_sss3, 'A'),
    ('OGS275', 'Waris', 'Waheed', cid_sss3, 'A'),
    ('OGS276', 'Joshua', 'IniworikaboOforie', cid_sss3, 'A'),
    ('OGS277', 'Biggard C.', 'Amagwala', cid_sss3, 'A'),
    ('OGS278', 'Sunday S.', 'Ibitamuno', cid_sss3, 'A'),
    ('OGS279', 'Belina', 'Amagwala', cid_sss3, 'A'),
    ('OGS280', 'Esther S.M.', 'Tekena', cid_sss3, 'A'),
    ('OGS281', 'Sophia T.', 'Tobin', cid_sss3, 'A'),
    ('OGS282', 'Cherish I.', 'Reuben', cid_sss3, 'A'),
    ('OGS283', 'Omtebi', 'Solomon', cid_sss3, 'A'),
    ('OGS284', 'Favour', 'Asitonka', cid_sss3, 'A'),
    ('OGS285', 'Blessing Ibimina', 'Sampson', cid_sss3, 'A'),
    ('OGS286', 'Tamuno Pulo S.', 'Victor', cid_sss3, 'A'),
    ('OGS287', 'Hakeem', 'Barakat', cid_sss3, 'A'),
    ('OGS288', 'Blessing Ibinabo', 'Boma', cid_sss3, 'A'),
    ('OGS289', 'Favour Emmy', 'Alali', cid_sss3, 'A'),
    ('OGS290', 'Precious', 'Tochkwu', cid_sss3, 'A'),
    ('OGS291', 'Oteluma', 'Julius', cid_sss3, 'A'),
    ('OGS292', 'Perpetual', 'Nwanchukwu', cid_sss3, 'A'),
    ('OGS293', 'Miracle Asukwu', 'Utting', cid_sss3, 'A'),
    ('OGS294', 'Wonderful', 'Godspower', cid_sss3, 'A'),
    ('OGS295', 'David', 'Esu', cid_sss3, 'A'),
    ('OGS296', 'Arinze', 'Ogarama', cid_sss3, 'A'),
    ('OGS297', 'Tamunodipriye', 'Solomon', cid_sss3, 'A'),
    ('OGS298', 'Ibiye', 'Emmanuel', cid_sss3, 'A'),
    ('OGS299', 'Tamunotonye', 'Ibibia', cid_sss3, 'A'),
    ('OGS300', 'Favour', 'Benjamin', cid_sss3, 'A'),
    ('OGS301', 'Tamunodipriye', 'Charles', cid_sss3, 'A'),
    ('OGS302', 'Peter', 'Cecilia', cid_sss3, 'A'),
    ('OGS303', 'Princewill Tonye', 'Ogan', cid_sss3, 'A'),
    ('OGS304', 'Ibinabo', 'Tam-Gudi', cid_sss3, 'A'),
    ('OGS305', 'John', 'Tamunokuro', cid_sss3, 'A'),
    ('OGS306', 'David', 'David', cid_sss3, 'A'),
    ('OGS307', 'Ogan', 'Emmanuel', cid_sss3, 'A'),
    ('OGS308', 'Raphael', 'David', cid_sss3, 'A')
  ) AS t(admission_number, first_name, last_name, class_id_val, section_val)
  LOOP
    v_email := lower(regexp_replace(student.first_name || '.' || student.last_name || '.' || student.admission_number || '@student.okrika.edu.ng', '\s+', '', 'g'));

    SELECT id INTO v_id FROM auth.users WHERE email = v_email;

    IF v_id IS NULL THEN
      v_id := gen_random_uuid();
      INSERT INTO auth.users (
        id, instance_id, aud, role, email, encrypted_password,
        email_confirmed_at, created_at, updated_at,
        raw_user_meta_data, raw_app_meta_data,
        confirmation_token, recovery_token, email_change_token_new,
        email_change, is_sso_user, deleted_at
      ) VALUES (
        v_id,
        '00000000-0000-0000-0000-000000000000',
        'authenticated', 'authenticated',
        v_email,
        extensions.crypt('School@2025', extensions.gen_salt('bf')),
        now(), now(), now(),
        jsonb_build_object('first_name', student.first_name, 'last_name', student.last_name, 'role', 'student'),
        '{"provider":"email","providers":["email"]}'::jsonb,
        '', '', '', '', false, null
      );
    END IF;

    INSERT INTO public.profiles (
      id, school_id, role, first_name, last_name, email, is_active
    ) VALUES (
      v_id, v_school_id, 'student',
      student.first_name, student.last_name, v_email, true
    )
    ON CONFLICT (id) DO UPDATE SET
      school_id  = EXCLUDED.school_id,
      role       = EXCLUDED.role,
      first_name = EXCLUDED.first_name,
      last_name  = EXCLUDED.last_name,
      email      = EXCLUDED.email;

    INSERT INTO public.students (
      id, school_id, admission_number, first_name, last_name, class_id, section, status
    ) VALUES (
      v_id, v_school_id, student.admission_number,
      student.first_name, student.last_name,
      student.class_id_val, student.section_val, 'active'
    )
    ON CONFLICT (school_id, admission_number) DO UPDATE SET
      first_name = EXCLUDED.first_name,
      last_name  = EXCLUDED.last_name,
      class_id   = EXCLUDED.class_id,
      section    = EXCLUDED.section;

  END LOOP;
END $$;
